services:
  comfyui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8188:8188"
      - "8787:8787"
    volumes:
      - ./workflows:/app/workflows
    environment:
      - COMFYUI_SERVER=http://localhost:8188
      - WS_SERVER=ws://localhost:8188
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
