FROM nvcr.io/nvidia/cuda:12.4.0-devel-ubuntu22.04

# Install system dependencies
RUN apt-get update && apt-get install -y build-essential ffmpeg git \
    python3 python3-dev python3-pip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy your application files
COPY app.py .
COPY requirements.txt .

# Install dependencies
RUN pip3 install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["python3", "app.py"]