apiVersion: apps/v1
kind: Deployment
metadata:
  name: comfy-image-generation-caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comfy-image-generation
  template:
    metadata:
      labels:
        app: comfy-image-generation
    spec:
      containers:
        - name: caddy
          image: caddy:latest
          ports:
            - containerPort: 8787
          volumeMounts:
            - name: comfy-image-generation-caddy-config
              mountPath: /etc/caddy/Caddyfile
              subPath: Caddyfile
      volumes:
        - name: comfy-image-generation-caddy-config
          configMap:
            name: comfy-image-generation-caddy-config
---
apiVersion: v1
kind: Service
metadata:
  name: comfy-image-generation-caddy-service
spec:
  type: LoadBalancer
  selector:
    app: comfy-image-generation
  ports:
    - name: comfy-image-generation-http
      protocol: TCP
      port: 8787
      targetPort: 8787
