apiVersion: apps/v1
kind: Deployment
metadata:
  name: comfy-image-generation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comfy-image-generation
  template:
    metadata:
      labels:
        app: comfy-image-generation
    spec:
      containers:
        - name: comfy-image-generation
          image: gcr.io/citric-lead-450721-v2/comfy-image-generation:1.0.1
          ports:
            - containerPort: 8188  # ComfyUI's default port
            - containerPort: 8787  # Your API port
          env:
            - name: COMFYUI_SERVER
              value: "http://localhost:8188"
            - name: WS_SERVER
              value: "ws://localhost:8188"
          resources:
            limits:
              nvidia.com/gpu: "1"
              cpu: "8"
              memory: "64Gi"
            requests:
              nvidia.com/gpu: "1"
              cpu: "4"
              memory: "48Gi"
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: comfy-image-generation-service
spec:
  type: LoadBalancer
  selector:
    app: comfy-image-generation
  ports:
    - name: comfyui
      port: 8188
      targetPort: 8188
    - name: api
      port: 8787
      targetPort: 8787
